import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ArticleShell from "@/components/ArticleShell";
import ArticleBody from "@/components/ArticleBody";
import JsonLd from "@/components/JsonLd";
import { posts, getPost, readingTime, toISO, firstParagraph } from "@/lib/content";
import { profile } from "@/lib/data";
import { absoluteUrl, site } from "@/lib/site";
import { breadcrumbJsonLd, personRef, plainDescription } from "@/lib/seo";

export const dynamicParams = false;
export const generateStaticParams = () => posts.map((p) => ({ slug: p.slug }));

export async function generateMetadata(props: PageProps<"/blog/[slug]">): Promise<Metadata> {
  const p = getPost((await props.params).slug);
  if (!p) return {};
  const description = plainDescription(firstParagraph(p.blocks));
  const url = absoluteUrl(`/blog/${p.slug}`);
  // Static hosts serve the extension-less generated image as octet-stream, which social crawlers reject,
  // so the static export falls back to the site-wide PNG.
  const ogImage = process.env.STATIC_EXPORT === "1" ? absoluteUrl("/opengraph-image.png") : absoluteUrl(`/blog/${p.slug}/opengraph-image`);
  return {
    title: p.title,
    description,
    alternates: { canonical: url },
    // Image is generated by app/blog/[slug]/opengraph-image.tsx; the URL is explicit so a sub-path deploy keeps its base path.
    openGraph: { type: "article", title: p.title, description, url, siteName: site.name, locale: site.locale, publishedTime: toISO(p.date), authors: [profile.name], section: p.category, images: [{ url: ogImage, width: 1200, height: 630, alt: p.title }] },
    twitter: { card: "summary_large_image", title: p.title, description, images: [ogImage] },
  };
}

export default async function PostPage(props: PageProps<"/blog/[slug]">) {
  const p = getPost((await props.params).slug);
  if (!p) notFound();
  const idx = posts.findIndex((x) => x.slug === p.slug);
  const others = [posts[idx + 1], posts[idx - 1]].filter(Boolean);
  const url = absoluteUrl(`/blog/${p.slug}`);
  const words = p.blocks.map((b) => (Array.isArray(b.x) ? b.x.flat().join(" ") : b.x)).join(" ").split(/\s+/).length;

  return (
    <ArticleShell back="/blog" backLabel="All posts">
      <JsonLd
        data={[
          {
            "@context": "https://schema.org",
            "@type": "BlogPosting",
            headline: p.title,
            description: plainDescription(firstParagraph(p.blocks), 300),
            datePublished: toISO(p.date),
            dateModified: toISO(p.date),
            articleSection: p.category,
            wordCount: words,
            inLanguage: "en",
            url,
            mainEntityOfPage: url,
            image: process.env.STATIC_EXPORT === "1" ? absoluteUrl("/opengraph-image.png") : absoluteUrl(`/blog/${p.slug}/opengraph-image`),
            author: personRef,
            publisher: personRef,
          },
          breadcrumbJsonLd([
            { name: "Home", path: "/" },
            { name: "Blog", path: "/blog" },
            { name: p.title, path: `/blog/${p.slug}` },
          ]),
        ]}
      />
      <article>
        <header className="space-y-3 border-b border-line px-6 py-9">
          <p className="font-mono text-[11px] tracking-widest text-soft">
            {p.category.toUpperCase()} · <time dateTime={toISO(p.date)}>{p.date.toUpperCase()}</time> · {readingTime(p.blocks)} MIN READ
          </p>
          <h1 className="font-serif text-3xl leading-tight sm:text-4xl">{p.title}</h1>
        </header>
        <ArticleBody blocks={p.blocks} />
      </article>
      <nav aria-label="More posts" className="border-t border-line px-6 py-6">
        <p className="mb-3 font-mono text-[11px] tracking-widest text-soft">KEEP READING</p>
        <ul className="grid gap-2 sm:grid-cols-2">
          {others.map((x) => (
            <li key={x.slug}>
              <Link href={`/blog/${x.slug}`} className="block rounded-md border border-line px-3 py-2 text-[13px] text-muted transition-colors hover:bg-[var(--hover)] hover:text-fg">{x.title}</Link>
            </li>
          ))}
        </ul>
      </nav>
    </ArticleShell>
  );
}
